javascript:(function(){
if(window.IrishmonkeLoaded){alert("Cheats already loaded!");return;}
window.IrishmonkeLoaded=true;

Object.defineProperty(navigator,'clipboard',{get:()=>undefined});
let iframe=document.createElement('iframe');
document.body.appendChild(iframe);
let oldLog=console.log;
console.log=iframe.contentWindow.console.log.bind(console);
iframe.remove();
console.log("%c Irishmonke Cheats %c\n By Irishmonke","color: #0bc2cf; font-size: 3rem","color: #8000ff; font-size: 1rem");

var wfcall=window.fetch.call;
if(window.fetch.call=function(){if(!arguments[1].includes("s.blooket.com/rc"))return wfcall.apply(this,arguments)},document.querySelector("script[src*='bfs/index.js']")&&!window.clearId){for(var e,t,a,o,r,i,n,s,e=document.createElement("iframe"),t=(document.body.appendChild(e),window.clearId=window.setInterval(()=>{},0));t--;)e.contentWindow.clearInterval.call(window,t);e.remove()}

function l(e,t={},...o){var a=document.createElement(e);if("object"==typeof t.style){let n="";for(let r in t.style)n+=`${r.replace(/[A-Z]/g,e=>"-"+e.toLowerCase())}: ${t.style[r]}; `;t.style=n}for(let i in t)a[i]=t[i];for(let l of o)a.append(l);return a}

let c={data:null,setItem(e,t){return e.split(".").reduce((e,o,a,n)=>(++a==n.length&&(e[o]=t),e[o]),this.data),localStorage.setItem("IrishmonkeSettings",JSON.stringify(this.data)),this.data},deleteItem(e){return e.split(".").reduce((e,t,o,a)=>(++o==a.length&&delete e[t],e[t]),this.data),localStorage.setItem("IrishmonkeSettings",JSON.stringify(this.data)),this.data},setData(e){this.data=e,localStorage.setItem("IrishmonkeSettings",JSON.stringify(this.data))}};

try{c.data=JSON.parse(localStorage.getItem("IrishmonkeSettings")||"{}")}catch{c.setData({})}

let p,u,h,m,$,g,y,b,v,_=l("div",{id:"IrishmonkeGUI",style:{top:Math.max(10,window.innerHeight-600)/2+"px",left:Math.max(10,window.innerWidth-1e3)/2+"px",transform:`scale(${c.data.scale||1})`,position:"fixed",height:"80%",width:"80%",maxHeight:"600px",maxWidth:"1000px",zIndex:"999999",display:"block"}},
p=l("style",{id:"variables",innerHTML:`:root {--backgroundColor: ${c.data?.theme?.backgroundColor||"rgb(11, 194, 207)"};--infoColor: ${c.data?.theme?.infoColor||"#9a49aa"};--cheatList: ${c.data?.theme?.cheatList||"#9a49aa"};--defaultButton: ${c.data?.theme?.defaultButton||"#9a49aa"};--disabledButton: ${c.data?.theme?.disabledButton||"#A02626"};--enabledButton: ${c.data?.theme?.enabledButton||"#47A547"};--textColor: ${c.data?.theme?.textColor||"white"};--inputColor: ${c.data?.theme?.inputColor||"#7a039d"};--contentBackground: ${c.data?.theme?.contentBackground||"rgb(64, 17, 95)"};}`}),
l("style",{innerHTML:'.alertList::-webkit-scrollbar{display:none;}.alertList{-ms-overflow-style: none;scrollbar-width: none;}.contentWrapper::-webkit-scrollbar{display:none;}.contentWrapper{-ms-overflow-style: none;scrollbar-width: none;}.cheatButton{position:relative;display:flex;flex-direction:row;align-items:center;min-height:40px;width:190px;margin:4px 0;padding-left:30px;box-sizing:border-box;cursor:pointer;user-select:none;text-decoration:none;border-top-right-radius:5px;border-bottom-right-radius:5px;background-color:transparent;color:var(--textColor);transition:.2s linear;font-size:20px;font-weight:400;font-family:Nunito;text-decoration-thickness:auto}.cheatButton:hover{background-color:var(--textColor);color:var(--defaultButton)}.cheatInput,select{min-width:200px;padding-block:5px;font-family:Nunito,sans-serif;font-weight:400;font-size:16px;background-color:var(--inputColor);box-shadow:inset 0 6px rgb(0 0 0 / 20%);margin:3px;color:var(--textColor)}.bigButton:hover{filter:brightness(110%);transform:translateY(-2px)}.bigButton:active{transform:translateY(2px)}.cheatList::-webkit-scrollbar{width:10px}.cheatList::-webkit-scrollbar-track{background:var(--cheatList)}.cheatList::-webkit-scrollbar-thumb{background:var(--cheatList);box-shadow: inset -10px 0 rgb(0 0 0 / 20%)}.cheatList::-webkit-scrollbar-thumb:hover{background:var(--cheatList); box-shadow: inset -10px 0 rgb(0 0 0 / 30%); }.scriptButton:hover{filter:brightness(120%)}.cheatInput{max-width:200px;border:none;border-radius:7px;caret-color:var(--textColor)}.cheatInput::placeholder{color:var(--textColor)}.cheatInput:focus,select:focus{outline:0}.cheatInput::-webkit-inner-spin-button,.cheatInput::-webkit-outer-spin-button{-webkit-appearance:none;margin:0}.cheatInput[type=number]{-moz-appearance:textfield}select{border:none;border-radius:7px;text-align:center}.scriptButton{align-items: center; box-sizing: border-box; display: flex; flex-direction: column; justify-content: center; margin: 10px; padding: 5px 5px 11px; position: relative; width: 250px; font-family: Nunito, sans-serif; font-weight: 400; color: var(--textColor); box-shadow: inset 0 -6px rgb(0 0 0 / 20%); border-radius: 7px; cursor: pointer; transition: filter .25s;}.tooltip::after {content: "";position: absolute;width: 10px;height: 10px;background-color: inherit;top: -5px;left: 50%;margin-left: -6px;transform: rotate(135deg)}'}),
u=l("div",{style:{width:"100%",height:"100%",position:"relative",outline:"3px solid #3a3a3a",borderRadius:"15px",overflow:"hidden"}},
l("div",{id:"background",style:{display:"block",top:"0",left:"0",height:"100%",overflowY:"hidden",overflowX:"hidden",position:"absolute",width:"100%",background:"var(--backgroundColor)",visibility:"visible"}},
l("div",{id:"backgroundImage",style:{backgroundImage:"url(https://ac.blooket.com/dashboard/65a43218fd1cabe52bdf1cda34613e9e.png)",display:"block",height:"200%",position:"absolute",width:"200%",top:"50%",left:"50%",backgroundPositionX:"-100px",backgroundPositionY:"-100px",backgroundSize:"550px",visibility:"visible",transform:"translate(-50%,-50%) rotate(15deg)",appearance:"none",opacity:"0.175"}})),
m=l("div",{id:"controls",style:{display:"flex",alignItems:"center",justifyContent:"center",paddingBottom:"8px",paddingInline:"15px",position:"absolute",left:"220px",top:"0",visibility:"visible",zIndex:"5",height:"52px",width:"max-content",background:"var(--infoColor)",boxShadow:"inset 0 -8px rgb(0 0 0 / 20%), 0 0 4px rgb(0 0 0 / 15%)",borderBottomRightRadius:"10px",color:"var(--textColor)",fontFamily:"Nunito, sans-serif",fontWeight:"700",userSelect:"text"},innerText:"Ctrl+E to hide | Ctrl+X to close | Drag here"}),
l("div",{id:"credits",style:{display:"flex",alignItems:"center",justifyContent:"center",paddingBottom:"8px",position:"absolute",right:"0",top:"0",visibility:"visible",zIndex:"5",height:"47px",width:"280px",background:"var(--infoColor)",boxShadow:"inset 0 -8px rgb(0 0 0 / 20%), 0 0 4px rgb(0 0 0 / 15%)",borderBottomLeftRadius:"10px",color:"var(--textColor)",fontFamily:"Nunito, sans-serif",fontWeight:"700",userSelect:"text"},innerHTML:"Irishmonke Cheats"}),$=l("div",{id:"controlButtons",style:{display:"flex",alignItems:"center",justifyContent:"center",position:"absolute",right:"0",bottom:"0",visibility:"visible",zIndex:"5",height:"55px",width:"165px",background:"#none",borderLeft:"3px solid black",borderTop:"3px solid black",borderTopLeftRadius:"10px",color:"white",fontFamily:"Nunito, sans-serif",fontWeight:"700",userSelect:"text",overflow:"hidden",pointerEvents:"all"}},
g=l("button",{style:{height:"55px",width:"55px",fontFamily:"Nunito",color:"white",backgroundColor:"#00a0ff",border:"none",fontSize:"2rem",cursor:"move"},innerHTML:"✥"}),
l("button",{style:{height:"55px",width:"55px",fontFamily:"Nunito",color:"white",backgroundColor:"grey",border:"none",fontSize:"2rem",fontWeight:"bolder",cursor:"pointer"},innerHTML:"-",onclick:function(){let e=!1;return()=>{for(var t of[...u.children])t!=$&&(e?t.style.display=t.style._display:(t.style._display=t.style.display,t.style.display="none"));u.style.height=e?"100%":"55px",u.style.width=e?"100%":"165px",_.style.top=parseInt(_.style.top)+(_.offsetHeight-55)*(e?-1:1)+"px",_.style.left=parseInt(_.style.left)+(_.offsetWidth-165)*(e?-1:1)+"px",_.style.pointerEvents=e?"unset":"none",e=!e}}()}),
l("button",{style:{height:"55px",width:"55px",fontFamily:"Nunito",color:"white",backgroundColor:"red",border:"none",fontSize:"2rem",fontWeight:"bolder",cursor:"pointer"},innerHTML:"X",onclick:()=>{_.remove();window.IrishmonkeLoaded=false;}})),
h=l("div",{className:"cheatList",style:{overflowY:"scroll",background:"var(--cheatList)",boxShadow:"inset -10px 0 rgb(0 0 0 / 20%)",zIndex:"5",width:"220px",position:"absolute",top:"0",left:"0",height:"100%",fontFamily:"Titan One",color:"var(--textColor)",fontSize:"40px",textAlign:"center",paddingTop:"20px",userSelect:"none",padding:"20px 10px 20px 0",boxSizing:"border-box",display:"flex",flexDirection:"column"},innerHTML:'<span style="text-shadow: 1px 1px rgb(0 0 0 / 40%); font-size: 0.8em;">Cheats</span>'}),
l("div",{className:"contentWrapper",style:{position:"absolute",left:"220px",top:"70px",overflowY:"scroll",width:"calc(100% - 220px)",height:"calc(100% - 70px)",borderRadius:"7px"}},
l("div",{id:"content",style:{position:"absolute",inset:"27px 50px 50px 50px"}},
y=l("div",{className:"tooltip",style:{position:"absolute",top:"0",left:"0",backgroundColor:"black",height:"fit-content",maxWidth:"300px",zIndex:"5",borderRadius:"7.5px",color:"white",display:"flex",justifyContent:"center",alignItems:"center",padding:"5px",paddingInline:"15px",pointerEvents:"none",opacity:"0",textAlign:"center"},innerText:"description"}),
b=l("div",{style:{alignItems:"center",boxSizing:"border-box",display:"flex",flexDirection:"row",flexWrap:"wrap",justifyContent:"space-evenly",padding:"20px 5px 20px",position:"relative",width:"100%",fontFamily:"Nunito, sans-serif",fontWeight:"400",color:"var(--textColor)",background:"var(--contentBackground)",boxShadow:"inset 0 -6px rgb(0 0 0 / 20%)",borderRadius:"7px"}},
v=l("div",{className:"headerText",style:{boxSizing:"border-box",display:"block",height:"45px",left:"-10px",padding:"4px 4px 8px",position:"absolute",top:"-28px",backgroundColor:"#ef7426",boxShadow:"0 4px rgb(0 0 0 / 20%), inset 0 -4px rgb(0 0 0 / 20%)",borderRadius:"7px"}},
l("div",{style:{alignItems:"center",boxSizing:"border-box",display:"flex",height:"100%",justifyContent:"center",padding:"0 15px",width:"100%",fontFamily:"Titan One, sans-serif",fontSize:"26px",fontWeight:"400",textShadow:"-1px -1px 0 #646464, 1px -1px 0 #646464, -1px 1px 0 #646464, 2px 2px 0 #646464",color:"white",background:"linear-gradient(#fcd843,#fcd843 50%,#feb31a 50.01%,#feb31a)",borderRadius:"5px"}})))))));

for(let f of document.querySelectorAll("#IrishmonkeGUI"))f.remove();

function w(e,t,o,a){let n=l("div",{className:"cheatButton",innerHTML:("string"==typeof t?`<img style="height: 30px; margin-right: 5px" src="${t}">`:t||"")+e,onclick:()=>k(n.innerText,o,a)});return h.appendChild(n),n.onclick}

async function k(e,t,o){b.innerHTML="",v.firstChild.innerText=e+(o?"":" Cheats"),b.append(v);for(let a=0;a<t.length;a++){let{name:n,description:r,type:i,inputs:s,enabled:c,run:p,element:d}=t[a];if(!d){let u=l("div",{className:"scriptButton",style:{background:"toggle"==i?c?"var(--enabledButton)":"var(--disabledButton)":"var(--defaultButton)"}},l("div",{className:"cheatName",innerHTML:n}));if(u.dataset.description=r,u.onclick=(function({target:e,key:t}){(e==u||e.classList.contains("cheatName")||"Enter"==t&&e.classList.contains("cheatInput"))&&(t=[...u.children].slice(1),p.apply(this,t.map(e=>"number"==e.type?parseInt("0"+e.value):"SELECT"==e.nodeName?JSON.parse(e.value):e.data||e.value)),"toggle"==i&&(u.style.background=this.enabled?"var(--enabledButton)":"var(--disabledButton)"))}).bind(t[a]),s?.length)for(let h=0;h<s.length;h++){var{name:m,type:$,options:g,min:y,max:f,value:_}=s[h];let k;try{k=await ("function"==typeof g?g?.():g)}catch{k=[]}if("options"==$&&k?.length){let w=document.createElement("select");k.forEach(e=>{var t=document.createElement("option");t.value=JSON.stringify(e?.value||e),t.innerHTML=e?.name||e,w.appendChild(t)}),u.appendChild(w)}else if("function"==$){let S=document.createElement("input");S.classList.add("cheatInput"),S.placeholder=m,S.style.textAlign="center";let x=(S.readOnly=!0,!1);S.onclick=async()=>{x||(S.value="Waiting for input...",x=!0,S.data=await s[h].function(e=>S.value=e+"..."),x=!1,S.value=S.value.slice(0,-3))},u.appendChild(S)}else(g=document.createElement("input")).classList.add("cheatInput"),"number"==$&&(g.type="number",g.min=y,g.max=f,g.value=_||(null!=y?y:0)),g.placeholder=m,g.style.textAlign="center",g.onkeyup=u.onclick,u.appendChild(g)}t[a].element=u}b.appendChild(t[a].element)}}

document.body.appendChild(_);

let rgbInterval=null;

function applyTheme(theme){
rgbInterval&&(clearInterval(rgbInterval),rgbInterval=null);
for(let key in theme){
c.setItem(`theme.${key}`,theme[key]);
}
p.innerHTML=`:root {--backgroundColor: ${theme.backgroundColor};--infoColor: ${theme.infoColor};--cheatList: ${theme.cheatList};--defaultButton: ${theme.defaultButton};--disabledButton: ${theme.disabledButton||"#A02626"};--enabledButton: ${theme.enabledButton||"#47A547"};--textColor: ${theme.textColor};--inputColor: ${theme.inputColor};--contentBackground: ${theme.contentBackground};}`
}

let themePresets={
"Default":{backgroundColor:"rgb(11, 194, 207)",infoColor:"#9a49aa",cheatList:"#9a49aa",defaultButton:"#9a49aa",disabledButton:"#A02626",enabledButton:"#47A547",textColor:"white",inputColor:"#7a039d",contentBackground:"rgb(64, 17, 95)"},
"Dark":{backgroundColor:"#1a1a1a",infoColor:"#2d2d2d",cheatList:"#2d2d2d",defaultButton:"#3d3d3d",disabledButton:"#A02626",enabledButton:"#47A547",textColor:"white",inputColor:"#3d3d3d",contentBackground:"#252525"},
"Ocean":{backgroundColor:"#006994",infoColor:"#004d6d",cheatList:"#004d6d",defaultButton:"#0080b3",disabledButton:"#A02626",enabledButton:"#47A547",textColor:"white",inputColor:"#0080b3",contentBackground:"#003d5c"},
"Purple":{backgroundColor:"#6a0dad",infoColor:"#4b0082",cheatList:"#4b0082",defaultButton:"#8b00ff",disabledButton:"#A02626",enabledButton:"#47A547",textColor:"white",inputColor:"#8b00ff",contentBackground:"#3d0066"},
"Neon":{backgroundColor:"#0a0a0a",infoColor:"#ff00ff",cheatList:"#00ffff",defaultButton:"#00ff00",disabledButton:"#ff0000",enabledButton:"#00ff00",textColor:"#00ffff",inputColor:"#ff00ff",contentBackground:"#1a1a1a"},
"Crypto Hack":{backgroundColor:"radial-gradient(#11581e,#041607)",infoColor:"#1a1a1a",cheatList:"#1a1a1a",defaultButton:"rgb(88, 175, 88)",disabledButton:"#A02626",enabledButton:"#0b601b",textColor:"white",inputColor:"rgb(0 0 0 / 25%)",contentBackground:"#11581e"},
"Fishing Frenzy":{backgroundColor:"linear-gradient(180deg,#9be2fe 0,#67d1fb)",infoColor:"#c8591e",cheatList:"#c8591e",defaultButton:"#ff751a",disabledButton:"#bf0e0e",enabledButton:"#2fb62f",textColor:"white",inputColor:"rgb(0 0 0 / 25%)",contentBackground:"radial-gradient(#02b0ea 40%, #1d86ea)"},
"Deceptive Dinos":{backgroundColor:"radial-gradient(rgba(220, 184, 86, 0), rgba(220, 184, 86, 0.4)), #ead49a",infoColor:"#af8942",cheatList:"#af8942",defaultButton:"#af8942",disabledButton:"#A02626",enabledButton:"#47A547",textColor:"white",inputColor:"rgb(0 0 0 / 10%)",contentBackground:"radial-gradient(rgba(1,104,162,.6),rgba(24,55,110,.5))"},
"Gold Quest":{backgroundColor:"linear-gradient(90deg, rgba(255,215,0,1) 0%, rgba(255,165,0,1) 100%)",infoColor:"#8B7500",cheatList:"#8B7500",defaultButton:"#FFD700",disabledButton:"#A02626",enabledButton:"#47A547",textColor:"white",inputColor:"rgb(0 0 0 / 25%)",contentBackground:"#B8860B"},
"Factory":{backgroundColor:"#3a3a3a",infoColor:"#a5aabe",cheatList:"#a5aabe",defaultButton:"#1563bf",disabledButton:"#9a49aa",enabledButton:"rgb(75, 194, 46)",textColor:"white",inputColor:"rgb(0 0 0 / 25%)",contentBackground:"#2d313d"},
"Cafe":{backgroundColor:"linear-gradient(90deg,rgba(200,0,0,.5) 50%,transparent 0) center / 50px 50px,linear-gradient(rgba(200,0,0,0.5) 50%,transparent 0) white center / 50px 50px",infoColor:"#ac7339",cheatList:"#ac7339",defaultButton:"#0bc2cf",disabledButton:"#A02626",enabledButton:"#47A547",textColor:"white",inputColor:"rgb(0 0 0 / 25%)",contentBackground:"rgb(64, 64, 64)"},
"Tower of Doom":{backgroundColor:"rgb(41, 41, 41)",infoColor:"#9a49aa",cheatList:"#9a49aa",defaultButton:"#333",disabledButton:"rgb(151, 15, 5)",enabledButton:"#4bc22e",textColor:"white",inputColor:"rgb(0 0 0 / 25%)",contentBackground:"#404040"},
"Monster Brawl":{backgroundColor:"rgb(78, 95, 124)",infoColor:"#374154",cheatList:"#374154",defaultButton:"rgb(45, 51, 67)",disabledButton:"#A02626",enabledButton:"#47A547",textColor:"white",inputColor:"rgb(0 0 0 / 25%)",contentBackground:"linear-gradient(0deg,#374154,#4f5b74)"},
"Tower Defense 2":{backgroundColor:"url(https://media.blooket.com/image/upload/v1676164454/Media/defense/backgroundTd1-02.svg) center / cover",infoColor:"#a33c22",cheatList:"#a33c22",defaultButton:"#40b1d8",disabledButton:"#A02626",enabledButton:"#47A547",textColor:"white",inputColor:"#3e8cbe",contentBackground:"#293c82"},
"Blook Rush":{backgroundColor:"repeating-linear-gradient(45deg,white,white 8%,#e6e6e6 0,#e6e6e6 16%)",infoColor:"#36c",cheatList:"#36c",defaultButton:"#36c",disabledButton:"#A02626",enabledButton:"#47A547",textColor:"white",inputColor:"rgb(0 0 0 / 25%)",contentBackground:"#888"},
"Santa's Workshop":{backgroundColor:"linear-gradient(180deg, #87CEEB 0%, #FFFFFF 100%)",infoColor:"#8B0000",cheatList:"#8B0000",defaultButton:"#228B22",disabledButton:"#A02626",enabledButton:"#47A547",textColor:"white",inputColor:"rgb(0 0 0 / 25%)",contentBackground:"#4169E1"}
};

let C={
global:[
{name:"Auto Answer",description:"Toggles auto answer on",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{var e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;var{state:{question:t,stage:o,feedback:a},props:{client:{question:n}}}=e;let r=t||n;if(!r)return;"typing"!=r.qType?("feedback"===o||a?document.querySelector('[class*="feedback"]')?.firstChild:[...document.querySelectorAll('[class*="answerContainer"]')][r.answers.map((e,t)=>r.correctAnswers.includes(e)?t:null).filter(e=>null!=e)[0]])?.click?.():Object.values(document.querySelector("[class*='typingAnswerWrapper']"))?.[1]?.children?._owner?.stateNode?.sendAnswer(r.answers[0])}catch{}},50))}},
{name:"Highlight Answers",description:"Toggles highlight answers on",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;let{state:t,props:o}=e;[...document.querySelectorAll('[class*="answerContainer"]')].forEach((e,a)=>{(t.question||o.client.question).correctAnswers.includes((t.question||o.client.question).answers[a])?e.style.backgroundColor="rgb(0, 207, 119)":e.style.backgroundColor="rgb(189, 15, 38)"})}catch{}},50))}},
{name:"Subtle Highlight",description:"Removes shadow from correct answers",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;let{state:t,props:o}=e;[...document.querySelectorAll('[class*="answerContainer"]')].forEach((e,a)=>{(t.question||o.client.question).correctAnswers.includes((t.question||o.client.question).answers[a])&&(e.style.boxShadow="unset")})}catch{}},50))}},
{name:"Use any Blook",description:"Allows you to play as any blook.",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e){alert("Run this on the lobby or dashboard!");return}if(e.state.blookData){let t=Object.entries;function o(o){e.setState({blookData:Object.keys(o).reduce((t,o)=>(t[o]=e.state.blookData[o]||1,t),{}),allSets:Object.values(o).reduce((e,t)=>(e.includes(t.set)||e.push(t.set),e),[])})}Object.entries=function(e){return e?.Chick&&(o(e),Object.entries=t),t.apply(this,arguments)},e.render()}else e.setState({unlocks:{includes:e=>1}})}catch{alert("Error: Make sure you're on the right page!")}}},
{name:"Every Answer Correct",description:"Makes every answer correct",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.freeQuestions&&(e.freeQuestions=e.freeQuestions.map(e=>({...e,correctAnswers:e.answers})));e.questions&&(e.questions=e.questions.map(e=>({...e,correctAnswers:e.answers})));e.props?.client?.questions&&(e.props.client.questions=e.props.client.questions.map(e=>({...e,correctAnswers:e.answers})))}catch{}}},
{name:"Freeze Leaderboard",description:"Freezes the leaderboard",type:"toggle",enabled:!1,data:null,run:function(){try{var e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;if(this.enabled)this.enabled=!1,clearInterval(this.data),this.data=null,e.props.liveGameController.removeVal(`c/${e.props.client.name}/tat`);else{this.enabled=!0;let t=()=>{e.props.liveGameController.setVal({path:`c/${e.props.client.name}/tat`,val:"Freeze"})};this.data=setInterval(t,25)}}catch{}}},
{name:"Remove Name Limit",description:"Removes 16 character name limit",run:function(){try{var e=document.querySelector('input[class*="nameInput"]');e&&(e.maxLength=120,alert("Name limit removed!"))}catch{alert("Error: Make sure you're on the name input screen!")}}},
{name:"Spam Buy Blooks",description:"Opens boxes rapidly",inputs:[{name:"Box Name",type:"text"},{name:"Amount",type:"number"}],run:async function(e,t){try{let o=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!o)return;for(let a=0;a<t;a++){await o.buyPack(!0,e),await new Promise(e=>setTimeout(e,100))}alert(`Opened ${t} boxes!`)}catch{alert("Error: Make sure you're on the market page!")}}},
{name:"Change Blook Ingame",description:"Changes your blook in game",inputs:[{name:"Blook Name",type:"text"}],run:function(e){try{let{props:t}=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.client.blook=e,t.liveGameController.setVal({path:`c/${t.client.name}/b`,val:e})}catch{alert("Error: Make sure you're in a game!")}}},
{name:"Sell Duplicates",description:"Sells all duplicate blooks",run:async function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;let t=0;for(let o in e.state.blookData)if(e.state.blookData[o]>1){e.setState({blook:o,numToSell:e.state.blookData[o]-1}),await e.sellBlook({preventDefault(){}},!0),await new Promise(e=>setTimeout(e,100)),t++}alert(`Sold ${t} duplicate blooks!`)}catch{alert("Error: Make sure you're on the blooks page!")}}}
],
voyage:[
{name:"Heist ESP",description:"Shows you what's under each chest during a heist",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null,Array.prototype.forEach.call(document.querySelectorAll(".chestESP"),e=>e.remove())):(this.enabled=!0,this.data=setInterval(()=>{try{let{stateNode:e}=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner;if(!e||"heist"!=e.state.stage)return;let t=Array.prototype.map.call(Array.prototype.slice.call(document.querySelector("[class*=prizesList]")?.children,1,4),e=>e.querySelector("img")?.src),o=Object.values(document.querySelector("[class*=modal]"))?.[0]?.return?.memoizedState?.memoizedState;if(!t||!o)return;for(let a of document.querySelectorAll("[class*=boxContent] > div"))a.remove();let n=Object.values(document.querySelector("[class*=modal]"))?.[0]?.return?.memoizedState?.next?.next?.memoizedState;Array.prototype.forEach.call(document.querySelector("[class*=chestsWrapper]")?.children,(e,a)=>{let r=e.firstChild?.firstChild;if(!r)return;if(n.includes(a))return r.style.opacity="";r.style.opacity="0.5";let i=document.createElement("div");i.innerHTML="<img src='"+t[2-o[a]]+"' style='max-width: 75%; max-height: 75%'></img>",i.className="chestESP",i.style.position="absolute",i.style.inset="0",i.style.display="grid",i.style.placeItems="center",i.style.pointerEvents="none",e.onclick=()=>{i.remove(),r.style.opacity=""},e.firstChild.prepend(i)})}catch{}},50))}},
{name:"Max Island Levels",description:"Maxes all island levels",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.setState({islandLevels:Array(e.state.islandLevels?.length||5).fill(5)})}catch{}}},
{name:"Set Doubloons",description:"Sets Doubloons",inputs:[{name:"Amount",type:"number"}],run:function(e){try{let{stateNode:t}=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner;if(!t)return;t.setState({doubloons:e}),t.props.liveGameController.setVal({path:`c/${t.props.client.name}/d`,val:e})}catch{}}},
{name:"Start Heist",description:"Starts a heist",run:function(){try{let{stateNode:e}=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner;if(!e)return;e.props.liveGameController.getDatabaseVal("c",function(t){let o=Object.entries(t||{}).reduce((t,[o,a])=>(o!=e.props.client.name&&t.push({name:o,blook:a.b,doubloons:a.d||0}),t),[]);if(0===o.length)return e.questionsToAnswer=1,void e.randomQ();let{name:a,blook:n,doubloons:r}=o.sort((e,t)=>t.doubloons-e.doubloons)[0];e.setState({stage:"heist",heistInfo:{name:a,blook:n},prizeAmount:Math.max(1e3,r)})})}catch{}}},
{name:"Swap Doubloons",description:"Swaps doubloons with top player",run:async function(){try{let{stateNode:e}=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner;if(!e)return;let t=Object.entries(await new Promise(t=>e.props.liveGameController.getDatabaseVal("c",t))).sort((e,t)=>t[1].d-e[1].d).filter(t=>t[0]!=e.props.client.name),o=t[0];if(!o)return;e.props.liveGameController.setVal({path:`c/${e.props.client.name}`,val:{b:e.props.client.blook,d:o[1].d,tat:`${o[0]}:${o[1].d-e.state.doubloons}`}}),e.setState({doubloons:o[1].d})}catch{}}}
],
gold:[
{name:"Chest ESP",description:"Shows what's in each chest",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{let{stateNode:e}=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner;if(!e||"prize"!==e.state.stage)return;e.state.choices.forEach((t,o)=>{var a=document.querySelector(`div[class*='choice${o+1}']`);if(a&&!a.querySelector("div")){var n=document.createElement("div");n.style.cssText="color:white;font-family:Eczar;font-size:2em;display:flex;justify-content:center;transform:translateY(200px)",n.innerText=t.text,a.append(n)}})}catch{}},50))}},
{name:"Hide Bad Chests",description:"Hides chests that make you lose gold",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{document.querySelectorAll('div[role="button"]').forEach(e=>{e.innerText.includes("Lose")&&(e.style.display="none")})},50))}},
{name:"Always Triple",description:"Makes every chest triple your gold",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.setState({choices:[{type:"multiply",val:3,text:"Triple Gold!",blook:"Unicorn"}]})}catch{}},50))}},
{name:"Auto Choose Best",description:"Automatically picks best chest",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{let{stateNode:e}=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner;if(!e||"prize"!=e.state.stage)return;let t=0,o=-1;for(let a=0;a<e.state.choices.length;a++){let n=e.state.choices[a],r=e.state.gold;"gold"==n.type?r=e.state.gold+(n.val||0):"multiply"==n.type?r=Math.round(e.state.gold*n.val)||e.state.gold:"divide"==n.type&&(r=Math.round(e.state.gold/n.val)||e.state.gold),(r||0)<=t||(t=r,o=a+1)}document.querySelector("div[class*='choice"+o+"']")?.click()}catch{}},50))}},
{name:"Set Gold",description:"Sets gold",inputs:[{name:"Amount",type:"number"}],run:function(e){try{var t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({gold:e,gold2:e}),t.props.liveGameController.setVal({path:"c/"+t.props.client.name,val:{b:t.props.client.blook,g:e}})}catch{}}},
{name:"Swap Gold",description:"Swaps gold with top player",run:async function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;let t=Object.entries(await new Promise(t=>e.props.liveGameController.getDatabaseVal("c",t))).sort((e,t)=>t[1].g-e[1].g).filter(t=>t[0]!=e.props.client.name)[0];t&&(e.props.liveGameController.setVal({path:`c/${e.props.client.name}`,val:{b:e.props.client.blook,g:t[1].g,tat:`${t[0]}:swap:${e.state.gold}`}}),e.setState({gold:t[1].g,gold2:t[1].g}))}catch{}}}
],
crypto:[
{name:"Password ESP",description:"Shows the correct password",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{var{state:e}=Object.values(document.querySelector("#app > div > div"))?.[1]?.children?.[1]?._owner?.stateNode;if(!e||"hack"!==e.stage)return;Array.from(document.querySelectorAll('[role="button"]')).forEach(t=>{t.textContent.trim()!==e.correctPassword.trim()?(t.style.outlineColor="rgba(255, 64, 64, 0.8)",t.style.backgroundColor="rgba(255, 64, 64, 0.8)",t.style.textShadow="0 0 1px #f33"):(t.style.outlineColor="rgba(0, 255, 0, 0.8)",t.style.backgroundColor="rgba(0, 255, 0, 0.8)",t.style.textShadow="0 0 1px #0f0")})}catch{}},50))}},
{name:"Auto Hack",description:"Automatically selects hack option",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.setState({choices:[{type:"hack",val:3,rate:.075,blook:"Mega Bot",text:"HACK"}]})}catch{}},50))}},
{name:"Auto Guess Password",description:"Automatically guesses password",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{let{stage:e,correctPassword:t}=Object.values(document.querySelector("#app > div > div"))?.[1]?.children?.[1]?._owner?.stateNode?.state;if("hack"!==e)return;Array.from(document.querySelectorAll("div")).filter(e=>e.innerHTML===t)[0]?.click()}catch{}},50))}},
{name:"Remove Hack",description:"Removes hack from your screen",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.setState({hack:""})}catch{}}},
{name:"Set Crypto",description:"Sets crypto",inputs:[{name:"Amount",type:"number"}],run:function(e){try{var t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({crypto:e,crypto2:e}),t.props.liveGameController.setVal({path:"c/"+t.props.client.name+"/cr",val:e})}catch{}}},
{name:"Set Password",description:"Sets your password",inputs:[{name:"Password",type:"text"}],run:function(e){try{var t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({password:e}),t.props.liveGameController.setVal({path:"c/"+t.props.client.name+"/p",val:e})}catch{}}},
{name:"Steal Crypto",description:"Steals crypto from top player",run:async function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;let t=Object.entries(await new Promise(t=>e.props.liveGameController.getDatabaseVal("c",t))).sort((e,t)=>t[1].cr-e[1].cr).filter(t=>t[0]!=e.props.client.name)[0];t&&(e.setState({crypto:e.state.crypto+t[1].cr,crypto2:e.state.crypto+t[1].cr}),e.props.liveGameController.setVal({path:`c/${e.props.client.name}`,val:{b:e.props.client.blook,p:e.state.password,cr:e.state.crypto+t[1].cr,tat:t[0]+":"+t[1].cr}}))}catch{}}}
],
fishing:[
{name:"Auto Reel",description:"Automatically reels in fish",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{let e=document.querySelector('[class*="reel"]');e&&!e.disabled&&e.click()},50))}},
{name:"Always Frenzy",description:"Always catch frenzy",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{let{stateNode:e}=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner;if(!e)return;e.props.liveGameController.setVal({path:`c/${e.props.client.name}`,val:{b:e.props.client.blook,w:e.state.weight,f:"Frenzy",s:!0}})}catch{}},50))}},
{name:"Remove Distractions",description:"Removes distractions",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode?.setState({party:""})}catch{}},50))}},
{name:"Set Weight",description:"Sets weight",inputs:[{name:"Amount",type:"number"}],run:function(e){try{var t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({weight:e}),t.props.liveGameController.setVal({path:"c/"+t.props.client.name+"/w",val:e})}catch{}}},
{name:"Set Lure",description:"Sets fishing lure level",inputs:[{name:"Lure (1-5)",type:"number",min:1,max:5}],run:function(e){try{Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode?.setState({lure:Math.max(Math.min(e-1,4),0)})}catch{}}}
],
factory:[
{name:"Max Upgrades",description:"Maxes all upgrades",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.setState({blookUpgrades:{megaBot:5,superBot:5,ultraBot:5}})}catch{}}},
{name:"Free Upgrades",description:"Makes all upgrades free",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.setState(t=>({...t,blooks:t.blooks.map(e=>({...e,price:[0,0,0,0]}))}))}catch{}}},
{name:"Max Blooks",description:"Maxes all blook levels",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.state.blooks&&e.state.blooks.forEach(e=>e.level=4)}catch{}}},
{name:"Remove Glitches",description:"Removes all glitches",run:function(){try{var e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.setState({bits:0,ads:[],hazards:[],color:"",lol:!1,joke:!1,slow:!1,dance:!1,glitch:"",glitcherName:"",glitcherBlook:""}),clearTimeout(e.adTimeout),clearInterval(e.hazardInterval),clearTimeout(e.nightTimeout),clearTimeout(e.glitchTimeout),clearTimeout(e.lolTimeout),clearTimeout(e.jokeTimeout),clearTimeout(e.slowTimeout),clearTimeout(e.danceTimeout),clearTimeout(e.nameTimeout)}catch{}}},
{name:"Set Cash",description:"Sets factory cash",inputs:[{name:"Amount",type:"number"}],run:function(e){try{var t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({cash:e}),t.props.liveGameController.setVal({path:"c/"+t.props.client.name+"/ca",val:e})}catch{}}}
],
defense:[
{name:"Max Tower Stats",description:"Maxes all tower stats",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.state.towers&&e.state.towers.forEach(e=>{e&&(e.range=100,e.fullCd=e.cd=0,e.damage=1e6)})}catch{}}},
{name:"Remove Obstacles",description:"Removes all obstacles",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.tiles=e.tiles.map(e=>e.fill(0))}catch{}}},
{name:"Remove Enemies",description:"Removes all enemies",run:function(){try{var e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.enemies=e.futureEnemies=[]}catch{}}},
{name:"Set Tokens",description:"Sets the amount of tokens you have",inputs:[{name:"Tokens",type:"number"}],run:function(e){try{let t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({tokens:e}),t.props.liveGameController.setVal({path:`c/${t.props.client.name}/t`,val:e})}catch{}}},
{name:"Set Round",description:"Sets the current round",inputs:[{name:"Round",type:"number"}],run:function(e){try{Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode?.setState({round:e})}catch{}}}
],
cafe:[
{name:"Max Items",description:"Maxes all cafe items",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.setState({items:Object.fromEntries(Object.entries(e.state.items).map(([e,t])=>[e,5]))})}catch{}}},
{name:"Stock Food",description:"Stocks all food to max",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.setState({foods:e.state.foods.map(e=>({...e,stock:99,level:5}))})}catch{}}},
{name:"Remove Customers",description:"Removes all customers",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.state.customers.forEach((t,o)=>{Object.keys(t).length&&e.removeCustomer(o,!0)})}catch{}}},
{name:"Reset Abilities",description:"Resets used abilities",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.setState({abilities:Object.fromEntries(Object.entries(e.state.abilities).map(([e,t])=>[e,5]))})}catch{}}},
{name:"Set Cash",description:"Sets cafe cash",inputs:[{name:"Amount",type:"number"}],run:function(e){try{let t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({cafeCash:e}),t.props.liveGameController.setVal({path:`c/${t.props.client.name}/ca`,val:e})}catch{}}}
],
racing:[
{name:"Instant Win",description:"Instantly win the race",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.setState({progress:e.state.goalAmount||100})}catch{}}},
{name:"Max Abilities",description:"Maxes all abilities",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.setState({abilities:{speed:10,jump:10,shield:10}})}catch{}}},
{name:"Set Progress",description:"Sets race progress",inputs:[{name:"Progress",type:"number"}],run:function(e){try{let t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({progress:e}),t.props.liveGameController.setVal({path:`c/${t.props.client.name}/pr`,val:e})}catch{}}}
],
flappy:[
{name:"God Mode",description:"Makes you invincible",type:"toggle",enabled:!1,run:function(){try{var e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;this.enabled?(this.enabled=!1,e&&e._componentWillUnmount&&(e.componentWillUnmount=e._componentWillUnmount)):(this.enabled=!0,e&&(e._componentWillUnmount=e.componentWillUnmount,e.componentWillUnmount=function(){}))}catch{}}},
{name:"Set Score",description:"Sets your score",inputs:[{name:"Score",type:"number"}],run:function(e){try{var t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({score:e})}catch{}}}
],
tower:[
{name:"Max Tower Stats",description:"Maxes all tower stats",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.state.towers&&e.state.towers.forEach(e=>{e&&(e.stats={damage:999999,range:999,cooldown:0},e.level=99)})}catch{}}},
{name:"Kill All Enemies",description:"Kills all enemies on screen",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e||!e.game?.current?.scene?.scenes?.[0])return;let t=e.game.current.scene.scenes[0];t.enemyQueue.length=0,t.physics.world.bodies.entries.forEach(e=>{e?.gameObject?.receiveDamage?.(e.gameObject.hp,1)})}catch{}}},
{name:"Set Coins",description:"Sets coins",inputs:[{name:"Amount",type:"number"}],run:function(e){try{let t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({coins:e})}catch{}}},
{name:"Max Cards",description:"Maxes all cards in deck",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.props.tower.cards.forEach(e=>{e.strength=20,e.charisma=20,e.wisdom=20})}catch{}}}
],
brawl:[
{name:"Instant Kill",description:"Sets all enemies health to 1",run:function(){try{for(let e of Object.values(document.querySelector("#app > div > div"))?.[1]?.children?.[0]?._owner?.stateNode?.game?.current?.scene?.scenes?.[0]?.physics?.world?.colliders?._active?.filter(e=>e.callbackContext?.toString().includes("invulnerableTime"))||[]){var t=e.object2;let o=t.classType.prototype.start;t.classType.prototype.start=function(){o.apply(this,arguments),this.hp=1},t.children.entries.forEach(e=>e.hp=1)}}catch{}}},
{name:"Invincibility",description:"Makes you invincible",run:function(){try{for(let e of Object.values(document.querySelector("#app > div > div"))?.[1]?.children?.[0]?._owner?.stateNode?.game?.current?.scene?.scenes?.[0]?.physics?.world?.colliders?._active?.filter(e=>e.callbackContext?.toString().includes("invulnerableTime"))||[])e.collideCallback=()=>{}}catch{}}},
{name:"Set XP",description:"Sets XP amount",inputs:[{name:"XP",type:"number"}],run:function(e){try{var t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({xp:e,totalXp:e}),t.xp=e,t.totalXp=e,t.props?.liveGameController.setVal({path:`c/${t.props.client.name}`,val:{b:t.props.client.blook,xp:e}})}catch{}}},
{name:"Max Abilities",description:"Maxes current abilities",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;for(var[t,o]of Object.entries(e.state.abilities))for(let a=0;a<10-o;a++)e.game.current.scene.scenes[0].game.events.emit("level up",t,e.state.abilities[t]++)}catch{}}}
],
dinos:[
{name:"Rock ESP",description:"Shows what's under rocks",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{let{stateNode:e}=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner;if(!e)return;let t=[...document.querySelector('[class*="rockButton"]')?.parentElement?.children||[]];t.every(e=>e.querySelector("div"))||e.setState({choices:[{type:"fossil",val:10},{type:"fossil",val:25},{type:"fossil",val:50},{type:"mult",val:1.5},{type:"mult",val:2}].sort(()=>.5-Math.random()).slice(0,3)},()=>{t.forEach((t,o)=>{let a=e.state.choices[o];t.querySelector("div")&&t.querySelector("div").remove();let n=document.createElement("div");n.style.cssText="color:white;font-family:Macondo;font-size:1em;display:flex;justify-content:center;transform:translateY(25px)",n.innerText="fossil"===a.type?`+${Math.round(a.val*e.state.fossilMult)} Fossils`:`x${a.val} Mult`,t.append(n)})})}catch{}},50))}},
{name:"Set Fossils",description:"Sets fossils",inputs:[{name:"Amount",type:"number"}],run:function(e){try{var t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({fossils:e}),t.props.liveGameController.setVal({path:`c/${t.props.client.name}`,val:{b:t.props.client.blook,f:e,ic:t.state.isCheating}})}catch{}}},
{name:"Set Multiplier",description:"Sets fossil multiplier",inputs:[{name:"Multiplier",type:"number"}],run:function(e){try{Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode?.setState({fossilMult:e})}catch{}}}
],
kingdom:[
{name:"Choice ESP",description:"Shows choice outcomes",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{let{stateNode:e}=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner;if(!e||"choice"!=e.state.phase)return;Array.prototype.forEach.call(document.querySelectorAll(".choiceESP"),e=>e.remove());let t=Array.prototype.reduce.call(document.querySelectorAll("[class*=statContainer]"),(e,t,o)=>(e[["materials","people","happiness","gold"][o]]=t,e),{});Object.keys(e.state.guest.yes||{}).forEach(o=>{if(null==t[o])return;let a=document.createElement("div");a.className="choiceESP",a.style="font-size: 24px; color: rgb(75, 194, 46); font-weight: bolder;",a.innerText=String(e.state.guest.yes[o]),t[o].appendChild(a)}),Object.keys(e.state.guest.no||{}).forEach(o=>{if(null==t[o])return;let a=document.createElement("div");a.className="choiceESP",a.style="font-size: 24px; color: darkred; font-weight: bolder;",a.innerText=String(e.state.guest.no[o]),t[o].appendChild(a)})}catch{}},50))}},
{name:"Max Stats",description:"Maxes all resources",run:function(){try{Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode?.setState({materials:100,people:100,happiness:100,gold:100})}catch{}}},
{name:"Skip Guest",description:"Skips current guest",run:function(){try{Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode?.nextGuest()}catch{}}},
{name:"Set Guests",description:"Sets guests seen",inputs:[{name:"Guests",type:"number"}],run:function(e){try{Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode?.setState({guestScore:e})}catch{}}}
],
royale:[
{name:"Auto Answer",description:"Auto answers questions",type:"toggle",enabled:!1,data:null,run:function(){this.enabled?(this.enabled=!1,clearInterval(this.data),this.data=null):(this.enabled=!0,this.data=setInterval(()=>{try{var e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e?.onAnswer?.(!0,e.props.client.question.correctAnswers[0])}catch{}},50))}}
],
rush:[
{name:"Set Blooks",description:"Sets blook count",inputs:[{name:"Blooks",type:"number"}],run:function(e){try{var t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({numBlooks:e}),t.isTeam?t.props.liveGameController.setVal({path:`a/${t.props.client.name}/bs`,val:e}):t.props.liveGameController.setVal({path:`c/${t.props.client.name}/bs`,val:e})}catch{}}},
{name:"Set Defense",description:"Sets defense (max 4)",inputs:[{name:"Defense",type:"number",max:4}],run:function(e){try{var t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;e=Math.min(e,4),t.setState({numDefense:e}),t.isTeam?t.props.liveGameController.setVal({path:`a/${t.props.client.name}/d`,val:e}):t.props.liveGameController.setVal({path:`c/${t.props.client.name}/d`,val:e})}catch{}}}
],
workshop:[
{name:"Remove Distractions",description:"Removes all distractions",run:function(){try{Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode?.setState({fog:!1,dusk:!1,wind:!1,plow:!1,blizzard:!1,force:!1,canada:!1,trees:[!1,!1,!1,!1,!1,!1,!1,!1,!1,!1]})}catch{}}},
{name:"Set Toys",description:"Sets toy count",inputs:[{name:"Toys",type:"number"}],run:function(e){try{var t=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!t)return;t.setState({toys:e}),t.props.liveGameController.setVal({path:`c/${t.props.client.name}`,val:{b:t.props.client.blook,t:e}})}catch{}}},
{name:"Set Toys Per Question",description:"Sets toys earned per question",inputs:[{name:"Toys",type:"number"}],run:function(e){try{Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode?.setState({toysPerQ:e})}catch{}}}
],
extras:[
{name:"Toggle Invert Colors",description:"Inverts all colors on page",run:function(){"invert()"==document.getElementsByTagName("html")[0].style.filter?document.getElementsByTagName("html")[0].style.filter="":document.getElementsByTagName("html")[0].style.filter="invert()";let e=document.querySelectorAll("a, img, video");for(let t=0;t<e.length;t++)("A"==e[t].nodeName&&(""!=e[t].style.background||""!=e[t].style.backgroundImage)||"A"!=e[t].nodeName)&&("invert()"==e[t].style.filter?e[t].style.filter="":e[t].style.filter="invert()")}},
{name:"History Flooder",description:"Floods browser history",inputs:[{name:"Amount",type:"number"}],run:function(e){let t=window.location.href;for(let o=1;o<=e;o++)history.pushState(0,0,o==e?t:o.toString());alert(`Flooded history with ${e} entries!`)}},
{name:"Auto Clicker",description:"Auto clicks (Press S to toggle)",inputs:[{name:"Delay (ms)",type:"number"}],run:function(e){let t=null,o=!0,a=0,n=0;function r(){t=setInterval(()=>{document.elementFromPoint(a,n)?.click?.()},e)}r(),document.addEventListener("mousemove",e=>{a=e.clientX,n=e.clientY},{passive:!0}),window.addEventListener("keydown",e=>{"s"===e.key&&(o?(clearInterval(t),t=null):r(),o=!o)})}},
{name:"Tab Cloaker",description:"Changes tab title and icon",inputs:[{name:"Icon URL",type:"text"},{name:"Title",type:"text"}],run:function(e,t){var o=document.querySelector("link[rel*='icon']")||document.createElement("link");o.type="image/x-icon",o.rel="shortcut icon",o.href=e||"https://www.blooket.com/favicon.ico",document.getElementsByTagName("head")[0].appendChild(o),document.title=t||"Blooket"}},
{name:"Panic Key",description:"Quickly close GUI (Alt+X)",run:function(){document.addEventListener("keydown",function(e){e.altKey&&"x"===e.key&&(e.preventDefault(),_.remove(),window.IrishmonkeLoaded=false,window.location.href="https://www.google.com")})}},
{name:"Screenshot Mode",description:"Hides GUI for screenshots",type:"toggle",enabled:!1,run:function(){this.enabled?(this.enabled=!1,_.style.display="block"):(this.enabled=!0,_.style.display="none")}}
],
host:[
{name:"Freeze Timer",description:"Stops the host timer",run:function(){try{let{stateNode:e}=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner;if(!e)return;clearInterval(e.timerInterval),e.timerInterval=setInterval(function(){e?.getClients?.(!1)},4e3)}catch{}}},
{name:"Remove Time Limit",description:"Removes host time limit",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.onAmountUpdate=function(t){let o=e.state.settings;o.amount=parseInt(t.target.value),e.setState({settings:o})}}catch{}}},
{name:"Kick All Players",description:"Kicks all players",run:async function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;let t=await e.props.liveGameController.getDatabaseVal("");e.props.liveGameController.setVal({path:"bu",val:Object.keys(t.c).reduce((e,t)=>(e[t]=1,e),t.bu?t.bu:{})}),e.props.liveGameController.setVal({path:"c",val:{}}),alert("Kicked all players!")}catch{alert("Error: Make sure you're hosting a game!")}}},
{name:"Toggle Spooky Mode",description:"Toggles spooky theme",run:function(){try{let e=Object.values(document.querySelector("#app>div>div"))?.[1]?.children?.[0]?._owner?.stateNode;if(!e)return;e.season=e.season?0:1,e.render()}catch{}}}
],
settings:[
{name:"RGB Theme",description:"Enables rainbow RGB theme",type:"toggle",enabled:!1,run:function(){if(this.enabled){this.enabled=!1,rgbInterval&&(clearInterval(rgbInterval),rgbInterval=null);let e=c.data?.theme?.backgroundColor||"rgb(11, 194, 207)";p.innerHTML=`:root {--backgroundColor: ${e};--infoColor: ${c.data?.theme?.infoColor||"#9a49aa"};--cheatList: ${c.data?.theme?.cheatList||"#9a49aa"};--defaultButton: ${c.data?.theme?.defaultButton||"#9a49aa"};--disabledButton: ${c.data?.theme?.disabledButton||"#A02626"};--enabledButton: ${c.data?.theme?.enabledButton||"#47A547"};--textColor: ${c.data?.theme?.textColor||"white"};--inputColor: ${c.data?.theme?.inputColor||"#7a039d"};--contentBackground: ${c.data?.theme?.contentBackground||"rgb(64, 17, 95)"};}`}else{this.enabled=!0;let t=0;rgbInterval=setInterval(()=>{t=(t+1)%360;let e=`hsl(${t}, 70%, 50%)`,o=`hsl(${(t+60)%360}, 70%, 40%)`,a=`hsl(${(t+120)%360}, 70%, 45%)`;p.innerHTML=`:root {--backgroundColor: ${e};--infoColor: ${o};--cheatList: ${o};--defaultButton: ${a};--disabledButton: #A02626;--enabledButton: #47A547;--textColor: white;--inputColor: ${a};--contentBackground: ${o};}`},50)}}},
{name:"Theme Selector",description:"Select from preset themes",inputs:[{name:"Theme",type:"options",options:Object.keys(themePresets)}],run:function(e){applyTheme(themePresets[e])}},
{name:"Background Color",description:"Changes the background color",inputs:[{name:"Color (hex)",type:"text"}],run:function(e){c.setItem("theme.backgroundColor",e);p.innerHTML=`:root {--backgroundColor: ${e};--infoColor: ${c.data?.theme?.infoColor||"#9a49aa"};--cheatList: ${c.data?.theme?.cheatList||"#9a49aa"};--defaultButton: ${c.data?.theme?.defaultButton||"#9a49aa"};--disabledButton: ${c.data?.theme?.disabledButton||"#A02626"};--enabledButton: ${c.data?.theme?.enabledButton||"#47A547"};--textColor: ${c.data?.theme?.textColor||"white"};--inputColor: ${c.data?.theme?.inputColor||"#7a039d"};--contentBackground: ${c.data?.theme?.contentBackground||"rgb(64, 17, 95)"};}`}},
{name:"Button Color",description:"Changes the button color",inputs:[{name:"Color (hex)",type:"text"}],run:function(e){c.setItem("theme.defaultButton",e);p.innerHTML=`:root {--backgroundColor: ${c.data?.theme?.backgroundColor||"rgb(11, 194, 207)"};--infoColor: ${c.data?.theme?.infoColor||"#9a49aa"};--cheatList: ${c.data?.theme?.cheatList||"#9a49aa"};--defaultButton: ${e};--disabledButton: ${c.data?.theme?.disabledButton||"#A02626"};--enabledButton: ${c.data?.theme?.enabledButton||"#47A547"};--textColor: ${c.data?.theme?.textColor||"white"};--inputColor: ${c.data?.theme?.inputColor||"#7a039d"};--contentBackground: ${c.data?.theme?.contentBackground||"rgb(64, 17, 95)"};}`}},
{name:"Text Color",description:"Changes the text color",inputs:[{name:"Color (hex)",type:"text"}],run:function(e){c.setItem("theme.textColor",e);p.innerHTML=`:root {--backgroundColor: ${c.data?.theme?.backgroundColor||"rgb(11, 194, 207)"};--infoColor: ${c.data?.theme?.infoColor||"#9a49aa"};--cheatList: ${c.data?.theme?.cheatList||"#9a49aa"};--defaultButton: ${c.data?.theme?.defaultButton||"#9a49aa"};--disabledButton: ${c.data?.theme?.disabledButton||"#A02626"};--enabledButton: ${c.data?.theme?.enabledButton||"#47A547"};--textColor: ${e};--inputColor: ${c.data?.theme?.inputColor||"#7a039d"};--contentBackground: ${c.data?.theme?.contentBackground||"rgb(64, 17, 95)"};}`}},
{name:"Reset Theme",description:"Resets all theme settings to default",run:function(){rgbInterval&&(clearInterval(rgbInterval),rgbInterval=null);c.deleteItem("theme");p.innerHTML=`:root {--backgroundColor: rgb(11, 194, 207);--infoColor: #9a49aa;--cheatList: #9a49aa;--defaultButton: #9a49aa;--disabledButton: #A02626;--enabledButton: #47A547;--textColor: white;--inputColor: #7a039d;--contentBackground: rgb(64, 17, 95);}`}},
{name:"GUI Scale",description:"Changes the GUI scale",inputs:[{name:"Scale (0.5-2)",type:"number",min:0.5,max:2,value:1}],run:function(e){c.setItem("scale",e);_.style.transform=`translate3d(${xOffset}px, ${yOffset}px, 0) scale(${e})`}},
{name:"Export Settings",description:"Exports settings to clipboard",run:async function(){await navigator.clipboard.writeText(JSON.stringify(c.data,null,2));alert("Settings copied to clipboard!")}},
{name:"Import Settings",description:"Imports settings from JSON",inputs:[{name:"JSON Data",type:"text"}],run:function(e){try{let t=JSON.parse(e);c.setData(t);alert("Settings imported! Reload GUI to apply.")}catch{alert("Invalid JSON!")}}}
]
};

w("Global","",C.global);
w("Voyage","",C.voyage);
w("Gold","",C.gold);
w("Crypto","",C.crypto);
w("Fishing","",C.fishing);
w("Factory","",C.factory);
w("Defense","",C.defense);
w("Cafe","",C.cafe);
w("Racing","",C.racing);
w("Flappy","",C.flappy);
w("Tower","",C.tower);
w("Brawl","",C.brawl);
w("Dinos","",C.dinos);
w("Kingdom","",C.kingdom);
w("Royale","",C.royale);
w("Rush","",C.rush);
w("Workshop","",C.workshop);
w("Extras","",C.extras);
w("Host","",C.host);
w("Settings","",C.settings);

let dragItem=_;
let active=false;
let currentX;
let currentY;
let initialX;
let initialY;
let xOffset=0;
let yOffset=0;

g.addEventListener("touchstart",dragStart,false);
g.addEventListener("touchend",dragEnd,false);
g.addEventListener("touchmove",drag,false);
g.addEventListener("mousedown",dragStart,false);
document.addEventListener("mouseup",dragEnd,false);
document.addEventListener("mousemove",drag,false);

function dragStart(e){if(e.type==="touchstart"){initialX=e.touches[0].clientX-xOffset;initialY=e.touches[0].clientY-yOffset}else{initialX=e.clientX-xOffset;initialY=e.clientY-yOffset}if(e.target===g){active=true}}

function dragEnd(e){initialX=currentX;initialY=currentY;active=false}

function drag(e){if(active){e.preventDefault();if(e.type==="touchmove"){currentX=e.touches[0].clientX-initialX;currentY=e.touches[0].clientY-initialY}else{currentX=e.clientX-initialX;currentY=e.clientY-initialY}xOffset=currentX;yOffset=currentY;setTranslate(currentX,currentY,dragItem)}}

function setTranslate(xPos,yPos,el){el.style.transform="translate3d("+xPos+"px, "+yPos+"px, 0) scale("+((c.data.scale||1))+")"}

document.addEventListener("keydown",function(e){if(e.ctrlKey&&e.key==="e"){e.preventDefault();_.style.display=_.style.display==="none"?"block":"none"}if(e.ctrlKey&&e.key==="x"){e.preventDefault();_.remove();window.IrishmonkeLoaded=false;}});

b.addEventListener("mouseover",function(e){if(e.target.classList.contains("scriptButton")||e.target.classList.contains("cheatName")){let t=e.target.classList.contains("scriptButton")?e.target:e.target.parentElement;y.innerText=t.dataset.description;y.style.opacity="1";y.style.top=t.offsetTop-y.offsetHeight-10+"px";y.style.left=t.offsetLeft+t.offsetWidth/2-y.offsetWidth/2+"px"}});

b.addEventListener("mouseout",function(e){if(e.target.classList.contains("scriptButton")||e.target.classList.contains("cheatName")){y.style.opacity="0"}});

console.log=oldLog;
alert("✅ Irishmonke Cheats Loaded!\n\n🎮 Ctrl+E to hide/show\n⌨️ Ctrl+X to close\n🍀 Works anytime - no timing needed!\n\n✨ 100+ Cheats Loaded!\n🌈 RGB Theme + 15 Presets\n🎨 Game-Specific Themes\n🔒 Anti-Detection\n📱 Bookmark Compatible");
})();
